#!/usr/bin/env bash
# Reviewer LoRA fine-tune scaffold (W10.6).
#
# Walks `cs dataset export` output through axolotl to produce a LoRA
# adapter that codifies *your* team's review style — closer to a senior
# engineer than a generic Sonnet review. Designed to run natively on a
# GX10's 128 GB unified memory; the same script works on smaller boxes
# by lowering --micro_batch_size and --num_epochs in the config below.
#
# Prereqs:
#   1. CLAUDESTRUCT_LOG_PROMPTS=1 was set on at least N runs of `cs review`
#      whose responses you'd like the fine-tune to imitate.
#   2. axolotl + a base model are already on the box. The Qwen2.5-Coder-7B
#      base is a good cost/quality starting point for code review:
#        ollama pull qwen2.5-coder:7b
#        pip install axolotl[deepspeed]
#
# This script is intentionally a thin wrapper. The real configuration
# lives in the YAML axolotl reads — adjust there, not here.
set -euo pipefail

repo="${REPO:-$(pwd)}"
out_dir="${OUT_DIR:-$repo/.claudestruct/finetune}"
dataset_path="$out_dir/reviewer-dataset.jsonl"
config_path="$out_dir/reviewer-axolotl.yml"
adapter_dir="$out_dir/lora-adapter"

mkdir -p "$out_dir"

if ! command -v cs >/dev/null 2>&1; then
    echo "finetune-reviewer: cs binary not on PATH" >&2
    exit 2
fi

# 1) Export the review-only dataset. `--since` defaults to the last
#    90 days so a stale 2-year-old run doesn't dominate the loss.
since="${SINCE:-$(date -u -d '90 days ago' +%Y-%m-%d 2>/dev/null || date -u -v-90d +%Y-%m-%d)}"

echo "finetune-reviewer: exporting dataset since $since"
cs dataset export \
    --out "$dataset_path" \
    --root "$repo" \
    --task review \
    --since "$since" \
    --format chat

rows="$(wc -l < "$dataset_path" | tr -d ' ')"
echo "finetune-reviewer: $rows training row(s) at $dataset_path"

if [[ "$rows" -lt 50 ]]; then
    cat <<EOF >&2
finetune-reviewer: warning — only $rows row(s) of training data.

  - LoRA adapters need ~hundreds of rows minimum to learn anything
    your base model doesn't already know.
  - Set CLAUDESTRUCT_LOG_PROMPTS=1 on more cs review runs first, or
    widen --since further (currently $since).

Continuing anyway so you can validate the pipeline.
EOF
fi

# 2) Drop a default axolotl config if the operator hasn't tuned one
#    already. The values target Qwen2.5-Coder-7B on a GX10; tweak
#    learning_rate / num_epochs / micro_batch_size for other hardware.
if [[ ! -f "$config_path" ]]; then
    cat > "$config_path" <<EOF
# Auto-generated by finetune-reviewer.sh — edit and re-run to retune.
base_model: Qwen/Qwen2.5-Coder-7B
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: $dataset_path
    type: chat_template
    chat_template: chatml
    field_messages: messages

dataset_prepared_path: $out_dir/last_run_prepared
output_dir: $adapter_dir

adapter: qlora
lora_r: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target_linear: true

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

micro_batch_size: 2
gradient_accumulation_steps: 4
num_epochs: 3
learning_rate: 0.0002
warmup_steps: 10
optimizer: adamw_torch
lr_scheduler: cosine

bf16: auto
fp16: false
flash_attention: true
gradient_checkpointing: true

logging_steps: 1
saves_per_epoch: 1
save_total_limit: 3
EOF
    echo "finetune-reviewer: wrote default axolotl config to $config_path"
fi

# 3) Run the fine-tune. axolotl's `accelerate launch` form picks up the
#    default GPU layout automatically; on a GX10 this lands on the
#    integrated 128 GB pool with no further flags.
if ! command -v axolotl >/dev/null 2>&1; then
    cat <<EOF >&2
finetune-reviewer: axolotl not installed. Try one of:
  pip install axolotl[deepspeed]
  pipx install axolotl
  uv pip install axolotl
Then rerun this script — config + dataset are already prepared.
EOF
    exit 0
fi

echo "finetune-reviewer: starting axolotl training"
axolotl train "$config_path"

echo "finetune-reviewer: done. LoRA adapter at $adapter_dir"
echo "finetune-reviewer: serve via ollama or vLLM, then point claudestruct"
echo "finetune-reviewer: at it via CLAUDESTRUCT_PROVIDER=openai + CLAUDESTRUCT_BASE_URL=…"
